export const projects = [
  {
    title: 'Ruang Kelas',
    description: "Ruang Kelas is a course registration app made by my team with Java Spring Boot for Metrodata Academy Final Project",
      image: '/images/5.png',
      tags: ['Web', 'Java', 'SpringBoot'],
    source: 'https://github.com/bapakfadil/java-ruangkelas',
    visit: 'http://httpstat.us/404',
    id: 0,
  },
  {
    title: 'Pokemon Site',
    description: "Pokemon Site is website that fetch PokemonAPI data and shows the data in informative ways",
      image: '/images/1.png',
      tags: ['Web', 'Javascript', 'PokemonAPI', 'Ajax'],
    source: 'https://github.com/bapakfadil/pokemon-site',
    visit: 'https://bapakfadil.github.io/pokemon-site/',
    id: 0,
  },
  {
    title: 'PromptAI',
    description:"PromptAI is a website to stores helpful ai prompt that can help users to solve problems or find solutions.",
    image: '/images/2.png',
    tags: ['NextJS', 'TailwindCSS'],
    source: 'https://github.com/bapakfadil/next-promptai',
    visit: 'https://next-promptai.vercel.app/',
    id: 1,
  },
  {
    title: 'Memories',
    description: "Memories is a web blog that stores photos and captions, so users can remember unforgettable memories",
      image: '/images/3.png',
      tags: ['MERN', 'MongoDB'],
    source: 'https://github.com/bapakfadil/mern-memories',
    visit: 'http://httpstat.us/404',
    id: 2,
  },
  {
    title: 'Movie Mania',
    description: "Movie Mania is website that fetch OMDBAPI data and shows the data in informative ways",
    image: '/images/4.png',
    tags: ['React', 'OMDBAPI'],
    source: 'https://github.com/bapakfadil/react_movieapp',
    visit: 'http://httpstat.us/404',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started my IT journey at Informatics Engineering UMT', },
  { year: 2021, text: 'Gettin hands-on with Web Development using PHP Laravel', },
  { year: 2022, text: 'Achieved Junior Web Developer Certification by BNSP and Learned Machine Learning', },
  { year: 2023, text: 'Learned new Tech Stacks (Java Spring, ReactJS, NextJS) and achieved Quality Assurance Bootcamp Scholarship from Binar SYNRGY x BCA Group', },
  { year: 2024, text: 'Apple Developer Student awardee?', },
];